# 各个云的存储价格（存储每GB多少钱）
storage_cost: [0.02,0.105,0.018,0.023,0.15,0.023]

# 各个云读流量的价格（读出每GB多少钱）
read_cost: [0.21,0.199,0.07,0.07,0.02,0.07]

# 各个云写流量的价格（写入每GB多少钱）
write_cost: [0.21,0.199,0.07,0.07,0.02,0.07]

# 云节点http服务的base_url, 拼接上/get,/put即是读写的endpoint
# 分别对应 google, rackspace, amazon, azure, aliyun, tencent
cloud_providers:
  - http://127.0.0.1:8080
  - http://127.0.0.1:8080
  - http://127.0.0.1:8080
  - http://127.0.0.1:8080
  - http://127.0.0.1:8080
  - http://127.0.0.1:8080

# 测试矩阵，cloud_placements * data_size * read
network_test:
  matrix:
    cloud_placements:
      - [1,0,1,0,0,0]
    data_sizes:
      - 1024
      - 2048
    reads:
      - true
      - false
  start_datetime: 2022-11-01 01:00:00
  end_datetime: 2022-11-01 01:05:00
  interval: 10
  N: 6
  k: 3
  n: 2